### ISSUE TITLE
Re ordenar luego de utilizar los diccionarios

### ISSUE THREAD

**Issue by ignaciolpaola** [nsidicarocep/DatosAbiertosCEP#10]
Buenas tardes.

Les escribo a partir de una inquietud que me surgió al utilizar las función de diccionario, `diccionario_sectores()`, sobre aquellas bases con apertura sectorial. Sucede que al emplear la misma, el data frame cambia su orden a partir de su variable de interés (puestos, salario medio o la que corresponda) dentro de cada sector, y no mantiene el criterio de orden original que es primero temporal y luego sectorial. De modo que, en el orden original, el primer grupo de filas corresponde al primer período temporal de cada uno de los sectores, luego al segundo período temporal y así sucesivamente; mientras que el criterio de orden al emplear el diccionario agrupa en las primeras filas a todas las entradas del primer sector ordenadas por su variable de interés, para luego pasar al segundo sector en orden numérico, y así sucesivamente.

Mi sugerencia es que quizás agregando un seteo de orden al final de la función diccionario, que contemple las nuevas variables creadas por esta función (de agregación sectorial mayor o de descripciones) pero que mantenga el orden original del dataframe, mejoraría el seguimiento de la operatoria y la comprensión de la función.

Gracias desde ya!

**Comment by nsidicarocep** [comment]
Estimado Ignacio, 

Antes que nada agradecerte por la sugerencia de parte del Centro de Estudios para la Producción, nos tomamos estas cosas muy en serio.
Ya hicimos el cambio que nos propusiste, así que vas a quedar eternamente inmortalizado en el paquete. Desde ahora el 7 de febrero será recordado como el día del pase a la inmortalidad de Ignacio Paola. 

Saludos!
Nicolás, tu compañero de banco
